package com.lesson.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LESSON".
 */
public class Lesson {

    private Long id;
    private String lesson_name;
    private String lesson_teacher;
    private String lesson_classroom;
    private String student_number;
    private String class_name;

    public Lesson() {
    }

    public Lesson(Long id) {
        this.id = id;
    }

    public Lesson(Long id, String lesson_name, String lesson_teacher, String lesson_classroom, String student_number, String class_name) {
        this.id = id;
        this.lesson_name = lesson_name;
        this.lesson_teacher = lesson_teacher;
        this.lesson_classroom = lesson_classroom;
        this.student_number = student_number;
        this.class_name = class_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLesson_name() {
        return lesson_name;
    }

    public void setLesson_name(String lesson_name) {
        this.lesson_name = lesson_name;
    }

    public String getLesson_teacher() {
        return lesson_teacher;
    }

    public void setLesson_teacher(String lesson_teacher) {
        this.lesson_teacher = lesson_teacher;
    }

    public String getLesson_classroom() {
        return lesson_classroom;
    }

    public void setLesson_classroom(String lesson_classroom) {
        this.lesson_classroom = lesson_classroom;
    }

    public String getStudent_number() {
        return student_number;
    }

    public void setStudent_number(String student_number) {
        this.student_number = student_number;
    }

    public String getClass_name() {
        return class_name;
    }

    public void setClass_name(String class_name) {
        this.class_name = class_name;
    }

}
