package com.lesson.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lesson.entity.Lesson;

import com.lesson.dao.LessonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lessonDaoConfig;

    private final LessonDao lessonDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lessonDaoConfig = daoConfigMap.get(LessonDao.class).clone();
        lessonDaoConfig.initIdentityScope(type);

        lessonDao = new LessonDao(lessonDaoConfig, this);

        registerDao(Lesson.class, lessonDao);
    }
    
    public void clear() {
        lessonDaoConfig.getIdentityScope().clear();
    }

    public LessonDao getLessonDao() {
        return lessonDao;
    }

}
